apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ec2-15-164-226-109.ap-northeast-2.compute.amazonaws.com/unn-project/nginx:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name:
